idf_component_register(
    SRCS
        "main.cpp"
        "core/system/system_manager.cpp"
        "core/system/system_info.cpp"
        "core/logging/logger.cpp"
        "core/monitoring/temperature/temperature_monitor.cpp"
        "core/monitoring/uptime/uptime_monitor.cpp"
        "wifi/wifi_manager/wifi_manager.cpp"
        "wifi/scanner/wifi_scanner.cpp"
        "wifi/analyzer/wifi_analyzer.cpp"
        "wifi/data/wifi_data.cpp"
        "network/ap/ap_manager/ap_manager.cpp"
        "core/config/config_manager.cpp"
        "network/webserver/web_server.cpp"
    INCLUDE_DIRS
        "."
    REQUIRES
        esp_driver_tsens
        esp_timer
        esp_wifi
        esp_event
        esp_netif
        nvs_flash
        esp_http_server
)